In [116]:
import csv
import random
import math
from numpy import shape
from numpy import array
from numpy import mean
from numpy import cov
from numpy import vstack
from numpy import delete
from numpy.linalg import eig
 
def loadCsv(filename):
    lines = csv.reader(open(filename, "rb"))
    dataset = list(lines)
    dataset.pop(0)
    for i in range(len(dataset)):
        if(dataset[i][0]=='HEALTHY'):
            dataset[i][0] = 0
        if(dataset[i][0]=='SURGERY'):
            dataset[i][0] = 1
        if(dataset[i][0]=='MEDICATION'):
            dataset[i][0] = 2
        for k in range(4):
            dataset[i][k] = float(dataset[i][k])
    dataset = array(dataset, dtype = 'float')
    return dataset

def getsep(dataset):
    #print dataset
    sep = [array([[0, 0, 0, 0]]) for i in range(3)]
    for i in range(3):
        sep[i] = vstack((sep[i], dataset[dataset[:,0] == i]))
        sep[i] = delete(sep[i], 0, axis = 0)
        sep[i] = delete(sep[i], 0, axis = 1)
    
    print sep[0].shape[1]
    
    return sep

def msd(sep):
    pm = m = sd = []
    for i in range(len(sep)):
        m.append(mean(sep[i], axis = 0))
        sd.append(cov(sep[i]))
    pm.append([m, sd])
#    print cov(sep[0]).shape
#    print pm

def prob()

filename = 'Medical_data.csv'
splitRatio = 0.67
dataset = loadCsv(filename)
print dataset
sep = getsep(dataset)
pm = msd(sep)


[[ 0.          1.63151556 -0.26444658  2.53456715]
 [ 1.          0.15395105  1.41953348  1.33312079]
 [ 0.          2.02172912  0.26204638  2.87997174]
 ...
 [ 0.          0.19320188  0.36039894  1.86764457]
 [ 0.          1.68409597 -0.0232182   3.30625768]
 [ 2.          0.9752179   2.30595893  0.22982688]]
3
